// frontend/app/(staff)/prescriptions/page.tsx
'use client'

import { useState } from 'react'
import {
  Card,
  CardContent,
  Box,
  Typography,
  Stack,
  Button,
  TextField,
  MenuItem,
} from '@mui/material'
import {
  usePatients,
  usePatientPrescriptions,
  usePatientAppointments,
  useCreatePrescription,
} from '@/lib/hooks'
import { PageHeader, Loading } from '@/components/ui'

export default function PrescriptionsPage() {
  const patients = usePatients('', 1)
  const [patientId, setPatientId] = useState('')
  const meds = usePatientPrescriptions(patientId)
  const appts = usePatientAppointments(patientId)
  const create = useCreatePrescription()
  const [f, setF] = useState({ medication: '', dosage: '', frequency: '', expiryDate: '' })
  const set = (k: string, v: string) => setF((x) => ({ ...x, [k]: v }))
  const appointmentId = appts.data?.[0]?.id

  return (
    <Box>
      <PageHeader title="Prescriptions" subtitle="Active medications tracker" />
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <TextField
            select
            label="Patient"
            value={patientId}
            onChange={(e) => setPatientId(e.target.value)}
            sx={{ minWidth: 280 }}
          >
            {patients.data?.items.map((p) => (
              <MenuItem key={p.id} value={p.id}>
                {p.fullName}
              </MenuItem>
            ))}
          </TextField>
        </CardContent>
      </Card>

      {patientId && (
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
          <Card>
            <CardContent>
              <Typography variant="h6" sx={{ mb: 1.5 }}>
                Active medications
              </Typography>
              {meds.isLoading ? (
                <Loading />
              ) : meds.data && meds.data.length ? (
                <Stack spacing={1}>
                  {meds.data.map((m) => (
                    <Box key={m.id} sx={{ bgcolor: 'grey.50', p: 1.5, borderRadius: 2 }}>
                      <Typography sx={{ fontWeight: 600, fontSize: 14 }}>
                        {m.medication} · {m.dosage}
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        {m.frequency}
                      </Typography>
                    </Box>
                  ))}
                </Stack>
              ) : (
                <Typography variant="body2" color="text.secondary">
                  No active prescriptions.
                </Typography>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardContent>
              <Typography variant="h6" sx={{ mb: 1.5 }}>
                Add prescription
              </Typography>
              {appointmentId ? (
                <Box
                  component="form"
                  onSubmit={(e: React.FormEvent) => {
                    e.preventDefault()
                    create.mutate(
                      { appointmentId, ...f, expiryDate: f.expiryDate || undefined },
                      {
                        onSuccess: () =>
                          setF({ medication: '', dosage: '', frequency: '', expiryDate: '' }),
                      },
                    )
                  }}
                >
                  <Stack spacing={1.5}>
                    <TextField
                      size="small"
                      label="Medication"
                      value={f.medication}
                      onChange={(e) => set('medication', e.target.value)}
                      required
                    />
                    <Stack direction="row" spacing={1}>
                      <TextField
                        size="small"
                        label="Dosage"
                        value={f.dosage}
                        onChange={(e) => set('dosage', e.target.value)}
                        required
                      />
                      <TextField
                        size="small"
                        label="Frequency"
                        value={f.frequency}
                        onChange={(e) => set('frequency', e.target.value)}
                        required
                      />
                    </Stack>
                    <TextField
                      size="small"
                      type="date"
                      label="Expiry"
                      slotProps={{ inputLabel: { shrink: true } }}
                      value={f.expiryDate}
                      onChange={(e) => set('expiryDate', e.target.value)}
                    />
                    <Button type="submit" variant="contained" disabled={create.isPending}>
                      Add prescription
                    </Button>
                    <Typography variant="caption" color="text.secondary">
                      Linked to the patient&apos;s most recent appointment.
                    </Typography>
                  </Stack>
                </Box>
              ) : (
                <Typography variant="body2" color="text.secondary">
                  This patient has no appointment to attach a prescription to.
                </Typography>
              )}
            </CardContent>
          </Card>
        </div>
      )}
    </Box>
  )
}

// frontend-angular/src/app/features/staff/prescriptions.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { MatButtonModule } from '@angular/material/button'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { ClinicApi } from '../../core/clinic.api'
import { PageHeaderComponent } from '../../shared/page-header.component'
import { LoadingComponent } from '../../shared/loading.component'

// Port of app/(staff)/prescriptions/page.tsx.
@Component({
  selector: 'app-prescriptions',
  standalone: true,
  imports: [
    FormsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    PageHeaderComponent,
    LoadingComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div>
      <app-page-header title="Prescriptions" subtitle="Active medications tracker" />
      <div class="brand-card brand-card--pad" style="margin-bottom:24px;">
        <mat-form-field appearance="outline" style="min-width:280px;" subscriptSizing="dynamic">
          <mat-label>Patient</mat-label>
          <mat-select [ngModel]="patientId()" (ngModelChange)="patientId.set($event)" name="patient">
            @for (p of patients.data()?.items ?? []; track p.id) {
              <mat-option [value]="p.id">{{ p.fullName }}</mat-option>
            }
          </mat-select>
        </mat-form-field>
      </div>

      @if (patientId()) {
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
          <div class="brand-card brand-card--pad">
            <h2 class="h-section" style="margin-bottom:12px;">Active medications</h2>
            @if (meds.isLoading()) {
              <app-loading />
            } @else if (meds.data()?.length) {
              <div class="stack">
                @for (m of meds.data()!; track m.id) {
                  <div class="soft-surface" style="padding:12px;">
                    <div style="font-weight:600;font-size:14px;">{{ m.medication }} · {{ m.dosage }}</div>
                    <div class="text-secondary" style="font-size:12px;">{{ m.frequency }}</div>
                  </div>
                }
              </div>
            } @else {
              <p class="text-secondary" style="font-size:14px;">No active prescriptions.</p>
            }
          </div>

          <div class="brand-card brand-card--pad">
            <h2 class="h-section" style="margin-bottom:12px;">Add prescription</h2>
            @if (appointmentId(); as apptId) {
              <form (ngSubmit)="add(apptId)">
                <div class="stack">
                  <mat-form-field appearance="outline" subscriptSizing="dynamic">
                    <mat-label>Medication</mat-label>
                    <input matInput [(ngModel)]="rx.medication" name="med" required />
                  </mat-form-field>
                  <div class="two">
                    <mat-form-field appearance="outline" subscriptSizing="dynamic">
                      <mat-label>Dosage</mat-label>
                      <input matInput [(ngModel)]="rx.dosage" name="dose" required />
                    </mat-form-field>
                    <mat-form-field appearance="outline" subscriptSizing="dynamic">
                      <mat-label>Frequency</mat-label>
                      <input matInput [(ngModel)]="rx.frequency" name="freq" required />
                    </mat-form-field>
                  </div>
                  <mat-form-field appearance="outline" subscriptSizing="dynamic">
                    <mat-label>Expiry</mat-label>
                    <input matInput type="date" [(ngModel)]="rx.expiryDate" name="expiry" />
                  </mat-form-field>
                  <button mat-flat-button color="primary" type="submit" [disabled]="create.isPending()">Add prescription</button>
                  <p class="text-secondary" style="font-size:12px;margin:0;">Linked to the patient's most recent appointment.</p>
                </div>
              </form>
            } @else {
              <p class="text-secondary" style="font-size:14px;">This patient has no appointment to attach a prescription to.</p>
            }
          </div>
        </div>
      }
    </div>
  `,
  styles: [
    `
      .stack {
        display: flex;
        flex-direction: column;
        gap: 12px;
      }
      .two {
        display: flex;
        gap: 8px;
      }
    `,
  ],
})
export class PrescriptionsComponent {
  private readonly clinic = inject(ClinicApi)

  protected readonly patientId = signal('')
  protected readonly patients = this.clinic.patients(() => ({ search: '', page: 1, bloodType: '' }))
  protected readonly meds = this.clinic.patientPrescriptions(() => this.patientId())
  protected readonly appts = this.clinic.patientAppointments(() => this.patientId())
  protected readonly create = this.clinic.createPrescription()

  protected readonly appointmentId = computed(() => this.appts.data()?.[0]?.id ?? '')
  protected rx = { medication: '', dosage: '', frequency: '', expiryDate: '' }

  protected add(appointmentId: string): void {
    this.create.mutate(
      { appointmentId, ...this.rx, expiryDate: this.rx.expiryDate || undefined },
      { onSuccess: () => (this.rx = { medication: '', dosage: '', frequency: '', expiryDate: '' }) },
    )
  }
}
